import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ar" | "en" | "it";

export const translations = {
  ar: {
    dir: "rtl" as const,
    navGallery: "المعرض",
    navArtist: "الرسامة",
    navAdmin: "الإدارة",
    heroQuote: "في الظلام، قبل أن تنبت أجنحتنا، نتعلم كيف نرسم النور.",
    loadingGallery: "يتم تحضير القاعة...",
    errorPaintings: "عذراً، تعذر تحميل اللوحات في الوقت الحالي.",
    emptyGallery: "القاعة فارغة حالياً. اللوحات في طريقها إلى العرض.",
    noDate: "بدون تاريخ",
    errorArtist: "عذراً، لم نتمكن من تحميل بيانات الرسامة.",
    instagram: "إنستغرام",
    twitter: "تويتر",
    email: "بريد إلكتروني",
    footerRights: "جميع الحقوق محفوظة للرسامة لونا شافي.",
    adminTitle: "لوحة الإدارة",
    adminSubtitle: "التحكم في المعرض الفني وبيانات الرسامة",
    tabPaintings: "اللوحات",
    tabArtist: "بيانات الرسامة",
    addPainting: "إضافة لوحة جديدة",
    editPainting: "تعديل اللوحة",
    fieldTitle: "عنوان اللوحة *",
    fieldImageUrl: "رابط الصورة (URL) *",
    fieldYear: "السنة",
    fieldOrder: "الترتيب",
    fieldDimensions: "الأبعاد",
    fieldDimensionsPlaceholder: "مثال: 100x120 سم",
    fieldMedium: "الخامة",
    fieldMediumPlaceholder: "مثال: زيت على قماش",
    fieldDescription: "الوصف",
    cancel: "إلغاء",
    saveChanges: "حفظ التعديلات",
    addButton: "إضافة اللوحة",
    confirmDelete: "هل أنت متأكد من حذف هذه اللوحة؟",
    deleteSuccess: "تم الحذف بنجاح",
    deleteSuccessDesc: "تم حذف اللوحة من المعرض",
    deleteError: "حدث خطأ",
    deleteErrorDesc: "لم يتم حذف اللوحة",
    updateSuccess: "تم التعديل بنجاح",
    updateSuccessDesc: "تم تحديث بيانات اللوحة",
    updateError: "خطأ",
    updateErrorDesc: "فشل في تحديث اللوحة",
    createSuccess: "تمت الإضافة بنجاح",
    createSuccessDesc: "تمت إضافة اللوحة الجديدة",
    createError: "خطأ",
    createErrorDesc: "فشل في إضافة اللوحة",
    artistNameAr: "الاسم بالعربية *",
    artistNameEn: "الاسم بالإنجليزية",
    artistSpecialty: "التخصص / اللقب",
    artistSpecialtyPlaceholder: "مثال: فنانة تشكيلية",
    artistPhoto: "رابط الصورة الشخصية",
    artistPhotoPlaceholder: "اتركه فارغاً لاستخدام الصورة الافتراضية",
    artistBio: "السيرة الذاتية *",
    artistInstagram: "إنستغرام (Username)",
    artistTwitter: "تويتر (Username)",
    artistEmail: "البريد الإلكتروني",
    saveArtist: "حفظ بيانات الرسامة",
    artistSaveSuccess: "تم الحفظ بنجاح",
    artistSaveSuccessDesc: "تم تحديث بيانات الرسامة",
    artistSaveError: "خطأ",
    artistSaveErrorDesc: "فشل في تحديث البيانات",
    notFound: "الصفحة غير موجودة",
    backHome: "العودة للمعرض",
    adminGateTitle: "منطقة خاصة",
    adminGateSubtitle: "هذه الصفحة مخصصة للمسؤول فقط",
    adminGatePasswordLabel: "كلمة المرور",
    adminGatePasswordPlaceholder: "أدخل كلمة المرور",
    adminGateSubmit: "دخول",
    adminGateError: "كلمة المرور غير صحيحة",
    adminGateLogout: "خروج",
  },
  en: {
    dir: "ltr" as const,
    navGallery: "Gallery",
    navArtist: "The Artist",
    navAdmin: "Admin",
    heroQuote: "In the dark, before our wings grow, we learn how to paint the light.",
    loadingGallery: "Preparing the gallery...",
    errorPaintings: "Sorry, the paintings could not be loaded at this time.",
    emptyGallery: "The gallery is currently empty. Paintings are on their way.",
    noDate: "No date",
    errorArtist: "Sorry, we could not load the artist's profile.",
    instagram: "Instagram",
    twitter: "Twitter",
    email: "Email",
    footerRights: "All rights reserved to artist Luna Shafie.",
    adminTitle: "Admin Panel",
    adminSubtitle: "Manage the art gallery and artist profile",
    tabPaintings: "Paintings",
    tabArtist: "Artist Profile",
    addPainting: "Add new painting",
    editPainting: "Edit painting",
    fieldTitle: "Painting title *",
    fieldImageUrl: "Image URL *",
    fieldYear: "Year",
    fieldOrder: "Order",
    fieldDimensions: "Dimensions",
    fieldDimensionsPlaceholder: "e.g. 100×120 cm",
    fieldMedium: "Medium",
    fieldMediumPlaceholder: "e.g. Oil on canvas",
    fieldDescription: "Description",
    cancel: "Cancel",
    saveChanges: "Save changes",
    addButton: "Add painting",
    confirmDelete: "Are you sure you want to delete this painting?",
    deleteSuccess: "Deleted",
    deleteSuccessDesc: "The painting has been removed from the gallery",
    deleteError: "Error",
    deleteErrorDesc: "The painting could not be deleted",
    updateSuccess: "Updated",
    updateSuccessDesc: "Painting details have been updated",
    updateError: "Error",
    updateErrorDesc: "Failed to update the painting",
    createSuccess: "Added",
    createSuccessDesc: "The new painting has been added",
    createError: "Error",
    createErrorDesc: "Failed to add the painting",
    artistNameAr: "Name in Arabic *",
    artistNameEn: "Name in English",
    artistSpecialty: "Specialty / Title",
    artistSpecialtyPlaceholder: "e.g. Visual artist",
    artistPhoto: "Profile photo URL",
    artistPhotoPlaceholder: "Leave empty to use default image",
    artistBio: "Biography *",
    artistInstagram: "Instagram (username)",
    artistTwitter: "Twitter (username)",
    artistEmail: "Email address",
    saveArtist: "Save artist profile",
    artistSaveSuccess: "Saved",
    artistSaveSuccessDesc: "Artist profile has been updated",
    artistSaveError: "Error",
    artistSaveErrorDesc: "Failed to update artist profile",
    notFound: "Page not found",
    backHome: "Back to Gallery",
    adminGateTitle: "Restricted Area",
    adminGateSubtitle: "This page is for administrators only",
    adminGatePasswordLabel: "Password",
    adminGatePasswordPlaceholder: "Enter password",
    adminGateSubmit: "Enter",
    adminGateError: "Incorrect password",
    adminGateLogout: "Log out",
  },
  it: {
    dir: "ltr" as const,
    navGallery: "Galleria",
    navArtist: "L'Artista",
    navAdmin: "Amministrazione",
    heroQuote: "Nel buio, prima che le ali crescano, impariamo come dipingere la luce.",
    loadingGallery: "Preparazione della galleria...",
    errorPaintings: "Spiacente, i dipinti non possono essere caricati al momento.",
    emptyGallery: "La galleria è momentaneamente vuota. I dipinti sono in arrivo.",
    noDate: "Senza data",
    errorArtist: "Spiacente, impossibile caricare il profilo dell'artista.",
    instagram: "Instagram",
    twitter: "Twitter",
    email: "Email",
    footerRights: "Tutti i diritti riservati all'artista Luna Shafie.",
    adminTitle: "Pannello di Amministrazione",
    adminSubtitle: "Gestisci la galleria d'arte e il profilo dell'artista",
    tabPaintings: "Dipinti",
    tabArtist: "Profilo Artista",
    addPainting: "Aggiungi nuovo dipinto",
    editPainting: "Modifica dipinto",
    fieldTitle: "Titolo del dipinto *",
    fieldImageUrl: "URL immagine *",
    fieldYear: "Anno",
    fieldOrder: "Ordine",
    fieldDimensions: "Dimensioni",
    fieldDimensionsPlaceholder: "es. 100×120 cm",
    fieldMedium: "Tecnica",
    fieldMediumPlaceholder: "es. Olio su tela",
    fieldDescription: "Descrizione",
    cancel: "Annulla",
    saveChanges: "Salva modifiche",
    addButton: "Aggiungi dipinto",
    confirmDelete: "Sei sicuro di voler eliminare questo dipinto?",
    deleteSuccess: "Eliminato",
    deleteSuccessDesc: "Il dipinto è stato rimosso dalla galleria",
    deleteError: "Errore",
    deleteErrorDesc: "Impossibile eliminare il dipinto",
    updateSuccess: "Aggiornato",
    updateSuccessDesc: "I dettagli del dipinto sono stati aggiornati",
    updateError: "Errore",
    updateErrorDesc: "Impossibile aggiornare il dipinto",
    createSuccess: "Aggiunto",
    createSuccessDesc: "Il nuovo dipinto è stato aggiunto",
    createError: "Errore",
    createErrorDesc: "Impossibile aggiungere il dipinto",
    artistNameAr: "Nome in arabo *",
    artistNameEn: "Nome in inglese",
    artistSpecialty: "Specialità / Titolo",
    artistSpecialtyPlaceholder: "es. Artista visiva",
    artistPhoto: "URL foto profilo",
    artistPhotoPlaceholder: "Lascia vuoto per usare l'immagine predefinita",
    artistBio: "Biografia *",
    artistInstagram: "Instagram (username)",
    artistTwitter: "Twitter (username)",
    artistEmail: "Indirizzo email",
    saveArtist: "Salva profilo artista",
    artistSaveSuccess: "Salvato",
    artistSaveSuccessDesc: "Il profilo dell'artista è stato aggiornato",
    artistSaveError: "Errore",
    artistSaveErrorDesc: "Impossibile aggiornare il profilo",
    notFound: "Pagina non trovata",
    backHome: "Torna alla Galleria",
    adminGateTitle: "Area Riservata",
    adminGateSubtitle: "Questa pagina è riservata agli amministratori",
    adminGatePasswordLabel: "Password",
    adminGatePasswordPlaceholder: "Inserisci la password",
    adminGateSubmit: "Accedi",
    adminGateError: "Password errata",
    adminGateLogout: "Esci",
  },
} satisfies Record<Language, Record<string, string> & { dir: "rtl" | "ltr" }>;

export type T = typeof translations.ar;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem("gallery-lang");
    return (stored as Language) || "ar";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("gallery-lang", l);
  };

  const t = translations[lang] as T;

  useEffect(() => {
    document.documentElement.setAttribute("dir", t.dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, t.dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}lo